# Services
services:
  # Apache + PHP
  apache_php_oo:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    container_name: proyecto_repaso_dws
    # Preparamos un volumen para almacenar nuestro código
    volumes:
      - ./src/:/var/www/html
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini-development
    expose:
      - 80
    ports:
      - 8088:80
    networks:
      - net1
    links:
      - mariadboo
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mariadboo:
    image: mariadb
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: dbrepaso
      MARIADB_USER: aaron
      MARIADB_PASSWORD: aaron
    volumes:
      - ./.docker/mariadb:/var/lib/mysql:Z
    ports:
      - 3308:3306
    networks:
      - net1

networks:
  net1:
    name: network1
    driver: bridge